# Generated by Django 5.2.5 on 2025-09-30 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другой')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('engine_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electric', 'Электро')], max_length=30)),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=4)),
                ('horsepower', models.PositiveIntegerField()),
                ('torque', models.PositiveIntegerField(help_text='Ньютон-метры')),
                ('transmission', models.CharField(choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('cvt', 'Вариатор'), ('dct', 'Робот')], max_length=20)),
                ('drive_type', models.CharField(choices=[('fwd', 'Передний'), ('rwd', 'Задний'), ('awd', 'Полный')], max_length=10)),
                ('length', models.PositiveIntegerField(help_text='мм')),
                ('width', models.PositiveIntegerField(help_text='мм')),
                ('height', models.PositiveIntegerField(help_text='мм')),
                ('wheelbase', models.PositiveIntegerField(help_text='мм')),
                ('weight', models.PositiveIntegerField(help_text='кг')),
                ('acceleration_0_100', models.DecimalField(decimal_places=2, help_text='секунды', max_digits=4)),
                ('max_speed', models.PositiveIntegerField(help_text='км/ч')),
                ('fuel_consumption', models.DecimalField(decimal_places=1, help_text='л/100км', max_digits=4)),
                ('safety_rating', models.PositiveSmallIntegerField(help_text='Рейтинг Euro NCAP (0-5 звезд)')),
                ('seats', models.PositiveSmallIntegerField(default=4)),
                ('has_air_conditioner', models.BooleanField(default=True)),
                ('has_multimedia', models.BooleanField(default=True)),
                ('body_type', models.CharField(choices=[('sedan', 'Седан'), ('coupe', 'Купе'), ('hatchback', 'Хэтчбек'), ('suv', 'Внедорожник'), ('roadster', 'Родстер'), ('pickup', 'Пикап')], max_length=30)),
                ('color', models.CharField(default='Черный', max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_app.owner')),
            ],
        ),
    ]
