# Generated by Django 5.2.5 on 2025-10-01 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=44, unique=True)),
                ('description', models.CharField(blank=True, max_length=550, null=True)),
                ('since', models.IntegerField(help_text='Год основания бренда', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2024)])),
            ],
        ),
    ]
